:compat-mode:
= Lab 12 - Build Accounts Service with Mysql/H2

Estimated time to complete: 30 minutes
[abstract]
--
In this lab we'll begin the second subproject of our complete cloud-native application architecture: _SpringTrader_, which implements the quotes fetching portion of a ``Trading-like'' application.
This microservice will provide the _Accounts Service_, which will allow us to create and browse user accounts.
We'll be using a relational model to represent the user accounts.
--

NOTE: The completed code for this lab can be found at `$COURSE_HOME/day_01/session_05/lab_12/complete/springtrader-accounts`.

== Exploring springtrader-accounts

. Change to the lab directory:
+
----
$ cd $COURSE_HOME/day_01/session_05/lab_12/initial/springtrader-accounts
----
+
and import the project (via `pom.xml`) into your IDE of choice.

. Explore the new `accounts` microservice:
- How many domain classes do you now have? Are there relationships between those classes?
- How many controller classes?
+
As for `spring-trader-quotes`, You can see that static web files are not included in `springtrader-accounts`. They will all be contained in a `web` microservice (dedicated to the web layer)



. Add the following to `application.properties` -- we'll eventually want to run multiple apps locally, so we are using a port that is different from 8080:
+
----
server.port=8082
security.basic.enabled=false
----

. To run the application locally you have to add H2 dependency to your `pom.xml` file.
----
<dependency>
	<groupId>com.h2database</groupId>
  	<artifactId>h2</artifactId>
    <scope>runtime</scope>
 </dependency>
----

. Open `src/main/resources/import.sql`. As a naming convention, Spring Boot automatically loads this file at startup time. You will therefore have 2 accounts created by default at application startup time.

. Run the application and open the url http://localhost:8082/account/1 into your web brower. You should see the following:
+
[source,json]
----
{"id":1,"address":"45 Test Dr.","passwd":"123","userid":"johnsmith3","email":"john@pivotal.io","creditcard":"999999999","fullname":"John Smith","authtoken":null,"creationdate":null,"openbalance":1200.50,"logoutcount":0,"balance":null,"lastlogin":null,"logincount":0}

----

== Preparing for Cloud Foundry

. Create the MySQL service.
+
----
$ cf cs p-mysql 100mb-dev springtrader-accounts-db
----
+
. Rebuild the JAR:
+
----
$ mvn clean package
----

== Deploying to Cloud Foundry

. Create an application manifest in `manifest.yml`:
+
[source,yml]
----
---
timeout: 180
instances: 1
memory: 512M
env:
    SPRING_PROFILES_DEFAULT: cloud
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
applications:
- name: accounts
  random-route: true
  path: target/accounts-1.0.0-SNAPSHOT.jar
  services: [ springtrader-accounts-db ]
----

. Push to Cloud Foundry:
+
----
$ cf push

...

Showing health and status for app accounts in org pivot-cqueiroz / space development as cqueiroz@pivotal.io...
OK

requested state: started
instances: 1/1
usage: 512M x 1 instances
urls: accounts-unexploited-boneset.cfapps.pez.pivotal.io
last uploaded: Mon Dec 7 21:01:55 UTC 2015
stack: cflinuxfs2
buildpack: java-buildpack=v3.3.1-offline-https://github.com/cloudfoundry/java-buildpack.git#063836b java-main java-opts open-jdk-like-jre=1.8.0_65 open-jdk-like-memory-calculator=2.0.0_RELEASE spring-auto-reconfiguration=1.10.0_RELEASE

     state     since                    cpu    memory           disk           details
#0   running   2015-12-07 06:02:51 PM   0.9%   456.4M of 512M   163.4M of 1G
----

.  Use what you've learned so far to insert a couple accounts into the MySQL instance through the REST service you just deployed (hint:  inspect the controller)

. Access the application using `curl` to make sure everything is working properly:
+
----
$ curl -i http://accounts-recompensatory-assassinator.cfapps.pez.pivotal.io/account/1
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8
Date: Mon, 07 Dec 2015 21:33:09 GMT
Server: Apache-Coyote/1.1
X-Application-Context: accounts:cloud:0
X-Cf-Requestid: 61792646-ccda-4538-4243-2f4e7e65b5bf
Content-Length: 284
Connection: close

{"id":1,"address":"45 Test Dr.","passwd":"123","userid":"johndoe",
"email":"anon@springsource.com","creditcard":"999999999","fullname":"John Doe",
"authtoken":null,"creationdate":"2015-12-07 21:32:00","openbalance":1200.50,"logoutcount":0,"balance":null,"lastlogin":null,"logincount":0}
----
