= Migrating a Monolith Application to Cloud Native

This course is derived from Matt Stine's link:https://github.com/mstine/CloudNativeArchitectureClass[course].

These course materials can be found link:https://github.com/S2EDU/MigratingAMonolithApplicationToCloudNative[here].

== Student Guide

=== Resources

Make sure you have installed the necessary software for this course - see link:sessions/setup.adoc[Setup].

The code we need is on github, so (in a Terminal/Cmd window) download it as follows:

----
$ git clone https://github.com/S2EDU/MigratingAMonolithApplicationToCloudNative
$ git fetch --all

$ git clone https://github.com/caxqueiroz/springtrader-monolith.git
$ git fetch --all

$ git clone https://github.com/caxqueiroz/springtrader-microservices.git
$ git fetch --all

----

For convenience, at this link:https://personal.filesanywhere.com/fs/v.aspx?v=8d6c6788586072ac73a3[link] you can find:

  . A PDF of these lab instructions
  . A zip file of the lab-instructions in HTML format - simply download, unpack and open `index.html`
  . A PDF of the slides - these are more detailed than the individual PDFs linked to each session (below) and are intended
    for reference after the course

=== Schedule

The lectures for this class are intentionally very light and are only intended to set the stage for the hands-on labs.
The overwhelming majority of our time will be spent writing code directly!

Approximate session times are as follows.  Lab times vary by group and may be different for your course.

==== Day One
9:00 AM - 10:30 AM:: *Session 1:* _Cloud-Native Architecture Overview and Building Twelve-Factor Apps with Spring Boot_
10:30 AM - 10:45 AM:: Morning Break
10:45 AM - 12:30 PM:: *Session 2:* _Operating Twelve-Factor Apps with Cloud Foundry_
12:30 PM - 1:30 PM:: Lunch
1:30 PM - 2:30 PM:: *Session 3:* _Spring Data JPA_
2:30 PM - 3:30 PM:: *Session 4:* _Splitting the Monolith_
3:30 PM - 3:45 PM:: Afternoon Break
3:45 PM - 5:00 PM:: *Session 5:* _Microservices with Polyglot Persistence_

==== Day Two
9:00 AM - 10:30 AM:: *Session 6:* _Cloud-Native Architecture Patterns: Part One_
10:30 AM - 10:45 AM:: Morning Break
10:45 AM - 12:30 AM:: *Session 7:* _Cloud-Native Architecture Patterns: Part Two_
12:30 PM - 1:30 PM:: Lunch
1:30 PM - 3:00 PM:: *Session 8:* _Securing Cloud-Native Applications_
3:00 PM - 3:15 PM:: Afternoon Break
3:15 PM - 4:00 PM:: *Session 9:* _The API Gateway Pattern_

=== Important Note on the Labs

Much of this course involves using command line tools rather than GUI
applications.  This may be unfamiliar to some of you.

In particular, Windows users will need to open and use Command windows. To do this
press `WK` + `R` and type `cmd` (where WK is the Windows Key).

To keep the labs simple, although we encourage you to use an IDE, we only use it
for creating and editing files.  In most cases we build using `mvn` directly.
We accept that this is not typical but it makes the lab instructions simpler.

=== Course Materials

==== Setup

** link:sessions/setup.adoc[Software Setup] for this course.

==== Day One

* Session 1 (link:sessions/day_01/session_01/session_01.pdf[Slides])
** link:sessions/day_01/session_01/lab_01/lab_01_boot_getting_started.adoc[Lab 1 - Getting Started with Spring Boot]
** link:sessions/day_01/session_01/lab_02/lab_02_boot_with_jetty.adoc[Lab 2 - Deploying a Web Application with an Embedded Container]
** link:sessions/day_01/session_01/lab_03/lab_03_boot_properties.adoc[Lab 3 - Externalizing Configuration with Spring Boot]
** link:sessions/day_01/session_01/lab_04/lab_04_boot_actuator.adoc[Lab 4 - Introspection, Monitoring, and Metrics using Spring Boot Actuator]
* Session 2 (link:sessions/day_01/session_02/session_02.pdf[Slides])
** link:sessions/day_01/session_02/lab_05/lab_05_cf_push.adoc[Lab 5 - From Zero to Pushing Your First Application]
** link:sessions/day_01/session_02/lab_06/lab_06_cf_service.adoc[Lab 6 - Binding to Cloud Foundry Services]
** link:sessions/day_01/session_02/lab_07/lab_07_cf_scaling.adoc[Lab 7 - Scaling Applications]
** link:sessions/day_01/session_02/lab_08/lab_08_cf_monitoring.adoc[Lab 8 - Monitoring Applications]
* Session 3 (link:sessions/day_01/session_03/session_03.pdf[Slides])
** link:sessions/day_01/session_03/lab_09/lab_09_rest.adoc[Lab 9 - Build a Hypermedia-Driven RESTful Web Service with Spring Data REST]
** link:sessions/day_01/session_03/lab_10/lab_10_service_binding.adoc[Lab 10 - Leveraging Spring Cloud Connectors for Service Binding]
* Session 4 (link:sessions/day_01/session_04/session_04.pdf[Slides])
** link:sessions/day_01/session_04/lab_10b/lab_bounded_contexts.adoc[Lab - Decomposition into microservices]
* Session 5 (link:sessions/day_01/session_05/session_05.pdf[Slides])
** link:sessions/day_01/session_05/lab_11/lab_11_quotes.adoc[Lab 11 - Build Quotes Service with MongoDB]
** link:sessions/day_01/session_05/lab_12/lab_12_accounts.adoc[Lab 12 - Build Account Service using MySQL]
** link:sessions/day_01/session_05/lab_13/lab_13_portfolio.adoc[Lab 13 - Build Portfolio Service with MySQL]

==== Day Two

* Session 6 (link:sessions/day_02/session_06/session_06.pdf[Slides])
** link:sessions/day_02/session_06/lab_14/lab_14_config_server.adoc[Lab 14 - Deploying and Using Spring Cloud Config Server]
** link:sessions/day_02/session_06/lab_15/lab_15_cloud_bus.adoc[Lab 15 - Refreshing Configuration with Spring Cloud Bus]
** link:sessions/day_02/session_06/lab_16/lab_16_discovery.adoc[Lab 16 - Leveraging Eureka for Service Discovery via Spring Cloud Netflix]

* Session 7 (link:sessions/day_02/session_07/session_07.pdf[Slides])
** link:sessions/day_02/session_07/lab_17/lab_17_load_balancing.adoc[Lab 17 - Client-Side Load Balancing with Ribbon]
** link:sessions/day_02/session_07/lab_18/lab_18_feign.adoc[Lab 18 - Declarative REST Clients with Feign]
** link:sessions/day_02/session_07/lab_19/lab_19_fault_tolerance.adoc[Lab 19 - Fault-Tolerance with Hystrix]
** link:sessions/day_02/session_07/lab_20/lab_20_hystrix_dashboard.adoc[Lab 20 - Monitoring Circuit Breakers with Hystrix Dashboard]

* Session 8 (link:sessions/day_02/session_08/session_08.pdf[Slides])
** link:sessions/day_02/session_08/lab_21/lab_21_oauth2_server.adoc[Lab 21 - Creating an OAuth2 Authorization Server]
** link:sessions/day_02/session_08/lab_22/lab_22_secure.adoc[Lab 22 - Securing a Resource Server with Spring Cloud Security]
