= Lab 15 - Refreshing Configuration with Spring Cloud Bus

[abstract]
--
The http://cloud.spring.io/spring-cloud-bus/[Spring Cloud Bus] links nodes in a distributed system with a lightweight message bus.
We'll use it, combined with a Spring bean scope called `@RefreshScope`, to broadcast configuration changes to our microservices.
The bus will be backed by a running instance of http://www.rabbitmq.com/[RabbitMQ].
--

You must have `curl` installed to complete this lab.

== Adding the Cloud Bus to the Test Config Client

. Change to the lab directory:
+
----
$ cd $COURSE_HOME/day_02/session_06/lab_15/initial/springtrader-config-client
----
+
and import the project (via `pom.xml`) into your IDE of choice.

. In `pom.xml`, replace the parent-pom declaration with the one below:
+
[source,xml]
---
<parent>
     <groupId>org.springframework.cloud</groupId>
     <artifactId>spring-cloud-starter-parent</artifactId>
     <version>1.0.0.RELEASE</version>
     <relativePath/>
     <!-- lookup parent from repository -->
 </parent>
---

. In `pom.xml`, add a dependency on `spring-cloud-starter-bus-amqp`:
+
[source,xml]
----
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-bus-amqp</artifactId>
</dependency>
----

. In the package `io.springtrader.configclient`, create the class `Greeter` and paste in the following source code:
+
[source,java]
----
@Component
@RefreshScope
public class Greeter {

    @Value("${greeting}")
    private String greeting;

    public String getGreeting() {
        return greeting;
    }
}
----

. Inside `io.springtrader.configclient` Create the class `GreetingController` as shown below:
+
[source,java]
----
@RestController
public class GreetingController {

    @Autowired
    Greeter greeter;

    @RequestMapping("/")
    public String greeter() {
        return greeter.getGreeting() + " World!";
    }

}
----

. Add the below code inside `src/main/resources/application.properties`:

----
spring.application.name=demo
----

. To run the application now, you'll need a local install of RabbitMQ. You can obtain one for your platform http://www.rabbitmq.com/download.html[here].

. A completed `springtrader-config-server` project has been placed in `$COURSE_HOME/day_02/session_06/lab_15/initial/springtrader-config-server` for your convenience.
+
Run the `springtrader-config-server` application
+

. Now that the config server application is running, you should also start the client application. Run `springtrader-config-client` from your IDE.

. Inside your web browser, connect to `spring-trader-client` on http://localhost:8080. You should see the below
+
----
Hello World!
----

. Now, open `demo.yml` from your config-repo and change the greeting:
+
----
greeting: Ohai
----

. Stage, commit, and push your changes:
+
----
git add .
git commit -m "swap greeting"
git push origin master
----

. In your web browser, connect to the config server on localhost:8888/demo/default. The updated value for `greeting` should show as below:
+
[source,json]
----
{
	"name":"default",
	"label":"",
	"propertySources":
	[
		{"name":"https://github.com/caxqueiroz/springtrader-config-repo.git/demo.yml",
		"source":{"greeting":"Ohai"}
	},
	...
	]
}
----

. Connect to the `config client` on localhost:8080 and see that the greeting *has not* been refreshed in the client applications:
+
----
Hello World!

----

NOTE: for Windows users: the below step requires to use curl. In case you are using Windows, a nice way to get access to `curl` is to launch the `git batch` console that should have been installed together with `git for windows`

. Now, `POST` a request to the `/bus/refresh` endpoint to trigger a configuration refresh event. You can only do this easily with `curl`:
+
----
$ curl -i -X POST localhost:8080/bus/refresh
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: demo
Content-Length: 0
Date: Wed, 06 Jan 2016 08:15:58 GMT
----

. In your web browser, connect to the config client on localhost:8080. The updated value for `greeting` should show as below:+
----
Ohai World!

----

== (optional) Update the Microservices to Use the Cloud Bus

. Create a Pivotal RabbitMQ service to back the Cloud Bus:
+
----
$ cf cs p-rabbitmq standard springtrader-cloud-bus-amqp
Creating service instance springtrader-cloud-bus-amqp in org pivot-cqueiroz / space development as cqueiroz@pivotal.io...
OK
----
+

. In your config repo, update the file `application.yml`, adding a new property:
+
----
configserver: true
bus: false
----
+
We'll use the refresh of this property in each of our microservices' environments to verify that the cloud bus is working.

. Stage, commit, and push your changes:
+
----
git add .
git commit -m "add bus property"
git push origin master
----

. Access the config server using `curl` (or a browser) to make sure the new property exists:
+
----
$ curl -i springtrader-config-server-succinct-electronarcosis.cfapps.pez.pivotal.io/application/default
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Date: Mon, 11 Jan 2016 02:20:19 GMT
Server: Apache-Coyote/1.1
X-Application-Context: springtrader-config-server:cloud:8080
X-Cf-Requestid: b5c59a87-e45b-4545-4333-93227b677a20
Content-Length: 178
Connection: close

{
	"name":"default",
	"label":"",
	"propertySources":[
		{
			"name":"https://github.com/caxqueiroz/springtrader-config-repo.git/application.yml",
			"source":{
						"configserver":true,
						"bus":false
			}
		}
	]
}
----

Each of the three microservice projects has been copied into `$COURSE_HOME/day_02/session_06/lab_15/initial`, and are in the state we left them at the end of link:../lab_14/lab_14.adoc[Lab 14].
You can either continue your existing projects or pickup from these copies.

For each project, perform the following steps (we'll do these once for the `springtrader-quotes` project in this guide):

. In `pom.xml`, add a dependency on `spring-cloud-starter-bus-amqp`:
+
----
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-bus-amqp</artifactId>
  <version>1.0.3.RELEASE</version>
</dependency>
----

. In `manifest.yml`, add a binding to `springtrader-cloud-bus-amqp`:
+
----
---
timeout: 180
instances: 1
memory: 1G
env:
    SPRING_PROFILES_ACTIVE: cloud
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
applications:
- name: springtrader-quotes
  random-route: true
  path: target/quotes-1.0.0-SNAPSHOT.jar
  services: [ springtrader-quotes-db, springtrader-config-service, springtrader-cloud-bus-amqp ] # <-- ADD THIS!
----
. In `application.yml`, add:
+
----
spring:
	rabbitmq:
		addresses: ${vcap.services.springtrader-cloud-bus-amqp.credentials.uri:amqp://${RABBITMQ_HOST:localhost}:${RABBITMQ_PORT:5672}}
----
. Build the JAR:
+
----
$ mvn package
----

. Push the application:
+
----
$ cf push
...

Showing health and status for app springtrader-quotes in org pivot-cqueiroz / space development as cqueiroz@pivotal.io...
OK

requested state: started
instances: 1/1
usage: 1G x 1 instances
urls: springtrader-quotes-untrafficked-iodism.cfapps.pez.pivotal.io
last uploaded: Mon Jan 11 02:39:17 UTC 2016
stack: cflinuxfs2
buildpack: java-buildpack=v3.3.1-offline-https://github.com/cloudfoundry/java-buildpack.git#063836b java-main java-opts open-jdk-like-jre=1.8.0_65 open-jdk-like-memory-calculator=2.0.0_RELEASE spring-auto-reconfiguration=1.10.0_RELEASE

     state     since                    cpu    memory         disk           details
#0   running   2016-01-11 10:40:05 AM   0.0%   520.1M of 1G   144.3M of 1G
----

. Verify the existence of our new `bus` property using `curl` (or a browser):
+
----
curl -i springtrader-quotes-unrefining-peanuts.cfapps.pez.pivotal.io/env
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Date: Mon, 11 Jan 2016 06:31:40 GMT
Server: Apache-Coyote/1.1
X-Application-Context: springtrader-quotes:cloud:0
X-Cf-Requestid: f24371d6-73de-4153-7990-235760316ed0
Connection: close
Transfer-Encoding: chunked

{

...

"configService:https://github.com/caxqueiroz/springtrader-config-repo.git/application.yml": {
  "bus": false,
  "configserver": true
},

...

}
----

Once you've completed these steps for all three microservices, we'll update the `bus` property to `true` and trigger a refresh across all three applications.

. Open `application.yml` from your config-repo and change the `bus` property to true:
+
----
configserver: true
bus: true
----

. Stage, commit, and push your changes:
+
----
git add .
git commit -m "change bus to true"
git push origin master
----

. Using `curl` (or a browser) test and see that the config server has updated with your new greeting:
+
----
curl -i springtrader-config-server-succinct-electronarcosis.cfapps.pez.pivotal.io/application/default
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Date: Mon, 11 Jan 2016 06:38:11 GMT
Server: Apache-Coyote/1.1
X-Application-Context: springtrader-config-server:cloud:8080
X-Cf-Requestid: f4329f45-e8e2-4fee-692c-efeb00ad1a5a
Content-Length: 177
Connection: close

{
    "label": "",
    "name": "default",
    "propertySources": [
        {
            "name": "https://github.com/caxqueiroz/springtrader-config-repo.git/application.yml",
            "source": {
                "bus": true,
                "configserver": true
            }
        }
    ]
}
----

. Using `curl`, `POST` a refresh event to the `springtrader-quotes` service:
+
----
$ curl -i -X POST springtrader-quotes-hallucal-splitter.cfapps.pez.pivotal.io/bus/refresh
TTP/1.1 200 OK
Content-Length: 0
Date: Mon, 11 Jan 2016 07:38:45 GMT
Server: Apache-Coyote/1.1
X-Application-Context: springtrader-quotes:cloud:0
X-Cf-Requestid: 7800e32f-da68-4df3-6cfc-8912003e6ac4
Content-Type: text/plain; charset=utf-8
Connection: close
----

. Using `curl` (or a browser), verify that `bus` has updated to `true` across all services:
+
----
$ curl -i springtrader-quotes-hallucal-splitter.cfapps.pez.pivotal.io/env
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Date: Mon, 11 Jan 2016 07:39:50 GMT
Server: Apache-Coyote/1.1
X-Application-Context: springtrader-quotes:cloud:0
X-Cf-Requestid: 563501ac-e471-46c3-58d1-40f485b870dd
Connection: close
Transfer-Encoding: chunked

{

...

"configService:https://github.com/caxqueiroz/springtrader-config-repo.git/application.yml": {
  "bus": true,
  "configserver": true
},

...

}

----
