= Lab 09a - Deploying the StringTrader Microservices version Application
[abstract]

--
We will now deploy the SpringTrader application you have been developing. We will use the Web microservices (provided) together with the services you have already built and we will deploy them on Pivotal Cloud Foundry. 
--



== Copying the 3 services  
. Copy the 3 services: Account, Quotes and Portfolio into *initial* folder.
+
----
cd $COURSE_HOME/day_02/session_05/lab_06b/initial/

cp -R $COURSE_HOME/day_01/session_05/lab_05a/complete/springtrader-quotes .
cp -R $COURSE_HOME/day_01/session_05/lab_05b/complete/springtrader-account .
cp -R $COURSE_HOME/day_01/session_05/lab_05c/complete/springtrader-portfolio .
----


== Deploy the Eureka Server to Cloud Foundry

. Create an application manifest in manifest.yml:
+
----
---
applications:
- name: springtrader-eureka
  host: springtrader-eureka-${random-word}
  memory: 512M
  instances: 1
  path: target/springtrader-eureka-0.0.1-SNAPSHOT.jar

----
. Push to Cloud Foundry:
+
----
cf push
----
. Make sure service is working. In a browser, visit the route assigned to your Eureka server and verify that everything is working properly:

. Create a user-provided service representing the Eureka server (be sure to use the route assigned to your Eureka server!):
+
-----
$ cf cups service-registry -p '{"uri":"http://springtrader-eureka-nonpatterned-insurgency.cfapps.pez.pivotal.io"}'
Creating user provided service service-registry in org pivot-cqueiroz / space development as cqueiroz@pivotal.io...
OK
-----

== Deploy SpringTrader 

. Create deploy.sh(bat) file. If you are using Unix add *#!/bin/sh* at the first file line. 
+
----
cf push -f quotes/manifest.yml
cf push -f accounts/manifest.yml
cf push -f portfolio/manifest.yml
cf push -f web/manifest.yml
----

== Testing it out

. Run the deploy command. 
+
----
./deploy.sh (or deploy.bat)
----

. In browser, go to the *webtrader* URL shown during cf push
