= Lab 1d - Introspection, Monitoring, and Metrics using Spring Boot Actuator

Estimated time to complete: 20 minutes

== Set up the Actuator

. Change to the lab directory (or build off of lab_01a, lab_01b, or lab_01c):
+
----
$ cd $COURSE_HOME/day_01/session_01/lab_01d/initial/hello-spring-boot
----

. Import the project's `pom.xml` into your editor/IDE of choice if you haven't already done so in a previous lab.

. To `pom.xml` add the following dependency to include the starter for Spring Boot Actuator:
+
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
----
. Run the application
. open this URL in  your browser: `http://localhost:8080/beans` (use right-click `Open in New Tab`).
You can see runtime information about your `Spring` beans. However it is hard to read.


== Adding proper JSon formatting


. Add the following configuration at the end of the class `HelloSpringBootApplication`:

(you are allowed to have 2 classes in the same file as long as only one of them is `public`)

----
@Configuration
class RestWsApplicationConfig {

    @Bean
    public Jackson2ObjectMapperBuilder jacksonBuilder() {
        Jackson2ObjectMapperBuilder builder = new Jackson2ObjectMapperBuilder();
        builder.indentOutput(true);
        return builder;
    }
}
----
. Run the application again and connect to `http://localhost:8080/beans`

== Introspection Endpoints

. Try out the following endpoints. The output is omitted here because it can be quite large:
+
http://localhost:8080/beans:: Dumps all of the beans in the Spring context.
http://localhost:8080/autoconfig:: Dumps all of the auto-configuration performed as part of application bootstrapping.
http://localhost:8080/configprops:: Displays a collated list of all `@ConfigurationProperties`.
http://localhost:8080/env:: Dumps the application's shell environment as well as all Java system properties.
http://localhost:8080/mappings:: Dumps all URI request mappings and the controller methods to which they are mapped.
http://localhost:8080/dump:: Performs a thread dump.
http://localhost:8080/trace:: Displays trace information (by default the last few HTTP requests).


== Health Indicators

Spring Boot provides an endpoint (http://localhost:8080/health) that allows for the notion of various health indicators.

. Normally, when Spring Security is not enabled, the `/health` endpoint will only expose an `UP` or `DOWN` value.
To simplify working with the endpoint for this lab, we will turn off its sensitivity.
Add the following to `src/main/resources/application.yml`:
+
----
endpoints:
  health:
    sensitive: false
----

. Create the class `io.pivotal.spring.hello.FlappingHealthIndicator` and into it paste the following code:
+
----
@Component
public class FlappingHealthIndicator implements HealthIndicator{

    private Random random = new Random(System.currentTimeMillis());

    @Override
    public Health health() {
        int result = random.nextInt(100);
        if (result < 50) {
            return Health.down().withDetail("flapper", "failure").withDetail("random", result).build();
        } else {
            return Health.up().withDetail("flapper", "ok").withDetail("random", result).build();
        }
    }
}
----
+
This demo health indicator will randomize the health check.

. Run the application
+

. Visit the application in the browser (http://localhost:8080/health), and verify that the output is similar to the following (and changes randomly!):
+
----
{
  status: "UP",
  flapping: {
    status: "UP",
    flapper: "ok",
    random: 69
  },
  diskSpace: {
    status: "UP",
    free: 113632186368,
    threshold: 10485760
  }
}

----
+
To learn more about the autogenerated metrics, visit http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-metrics.html.
